package com.example.jjomnawaProject.model.entity;

import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class Categories {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String name;
    @Column
    private Long p_id;
    @Column
    private Long depth;

    /*
    public String toString() {
        return "\nCategories{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", p_id=" + p_id +
                ", depth=" + depth +
                '}';
    }*/

    public Categories(String name, Long p_id, Long depth) {
        this.name = name;
        this.p_id = p_id;
        this.depth = depth;
    }

    /*
    drop table categories;
    create table categories (
        id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL unique,
        p_id number, -- 부모 카테고리를 참조
        depth number NOT NULL -- 대/중/소 카테고리 레벨
        --CONSTRAINT fk_parent FOREIGN KEY (p_id) REFERENCES categories(id) ON DELETE CASCADE
    );
    */
}
