package com.example.jjomnawaProject.model.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.sql.Timestamp;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class PriceLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "product_id", nullable = false)
    private Long productId;

    @Column(name = "price", nullable = false)
    private Double price;

    @Column(name = "price_timestamp", nullable = false)
    private Timestamp priceTimestamp;

    @ManyToOne
    @JoinColumn(name = "product_id", insertable = false, updatable = false)
    private Product product;

    @Override
    public String toString() {
        return "\nPriceLog{" +
                "id=" + id +
                ", productId=" + productId +
                ", price=" + price +
                ", priceTimestamp=" + priceTimestamp +
                ", product=" + product +
                '}';
    }

    /*
    drop table price_log;
    create table price_log (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id NUMBER NOT NULL,
        price NUMBER NOT NULL,
        price_timestamp TIMESTAMP NOT NULL,
        FOREIGN KEY (product_id) REFERENCES products(id)
    );
     */
}
