package com.example.jjomnawaProject.model.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.GenerationTime;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table
public class PriceLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "product_id", nullable = false)
    private Long productId;

    @Column(name = "price", nullable = false)
    private Long price;

    @Column(name = "price_timestamp", nullable = false)
    private LocalDateTime priceTimestamp;

    @PrePersist //엔티티가 데이터베이스에 처음 삽입되기 전에 호출됨
    protected void setPriceTimestamp() {
        priceTimestamp = LocalDateTime.now();
    }

    /*
    @ManyToOne
    @JoinColumn(name = "product_id", insertable = false, updatable = false)
    private Product product;
    */
    /*
    drop table price_log;
    create table price_log (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id NUMBER NOT NULL,
        price NUMBER NOT NULL,
        price_timestamp TIMESTAMP NOT NULL,
        FOREIGN KEY (product_id) REFERENCES products(id)
    );
     */
}
